blank_issues_enabled: true
contact_links:
  - name: Smithcoin Core Security Policy
    url: https://github.com/smithcoin/smithcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Smithcoin Core Developers
    url: https://smithcoincore.org
    about: Smithcoin Core homepage
